lst=[10,20,30,40,50,60,70,80,90,100,'mayank',True, 3.14, 0xFF, 0b1010, 0o77, 3+5j]
print(lst)
print(lst[13])
print(lst[3:6])
print(lst*2)
print(lst[::-1])
lst.append(200)
print(lst)
lst.insert(2, 150)
print(lst)
lst.remove('mayank')
lst.remove(True)
# lst.remove(3.14)
lst.remove(0xFF)
lst.remove(0b1010)
lst.remove(0o77)
lst.remove(3+5j)
print(lst)
del(lst[3])
print(lst)
lst.sort()
print(lst)
lst.sort(reverse=True)
print(lst)

# Assignement

countries = ['India', 'USA', 'Canada', 'Australia', 'Germany']
print(countries)
countries.append('Japan')
print(countries)
countries.insert(2, 'France')
print(countries)
countries.remove(countries[2])
print(countries)